# Generated by Django 4.1 on 2022-08-09 03:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app_anti_d', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGovernments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='disastername',
            name='mode',
            field=models.IntegerField(blank=True, choices=[(0, '訓練'), (1, '本番'), (2, 'その他')], null=True, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='disastername',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='災害名'),
        ),
    ]
