# Generated by Django 4.1 on 2022-08-09 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_anti_d', '0003_alter_localgovernments_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HearingReportsFromLocalGovernment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='タイトル')),
                ('reported_at', models.DateTimeField(blank=True, null=True, verbose_name='報告日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('disaster_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_anti_d.disastername')),
            ],
        ),
        migrations.AddField(
            model_name='localgovernments',
            name='hearing_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_anti_d.hearingreportsfromlocalgovernment'),
        ),
    ]
