# Generated by Django 4.1 on 2022-08-16 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_anti_d', '0005_remove_localgovernments_hearing_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireDepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HearingReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='タイトル')),
                ('reported_at', models.DateTimeField(blank=True, null=True, verbose_name='報告日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('disaster_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_anti_d.disastername', verbose_name='災害名')),
                ('heard_by_fire_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_anti_d.firedepartments')),
                ('heard_by_local_government', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_anti_d.localgovernments', verbose_name='聞き取り先')),
            ],
        ),
        migrations.DeleteModel(
            name='HearingReportsFromLocalGovernment',
        ),
    ]
